# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

create table "USER" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null
);

create table "BOARD" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not NULL,
  "user" bigint
);

create table "BOARD_X_LOCATION" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "location_id" bigint,
  "board_id" bigint
);

create table "LOCATION" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "city" varchar not null,
  "date" varchar not null,
  "temp" double not null,
  "text" varchar not null,
  "woeid" bigint,
  "board" bigint
);

# --- !Downs

drop table "people" if exists;
drop table "USER" if exists;
drop table "BOARD" if exists;
drop table "BOARD_X_LOCATION" if exists;
drop table "LOCATION" if exists;